"""added index original

Revision ID: e9a3dc01f8cb
Revises: 2590d75c6a0e
Create Date: 2022-12-24 16:38:48.855178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9a3dc01f8cb'
down_revision = '2590d75c6a0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_url_map_original'), 'url_map', ['original'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_map_original'), table_name='url_map')
    # ### end Alembic commands ###
